version: "3"

tasks:
  unit_tests:
    cmds:
      - go test -coverprofile coverage.out -coverpkg=./... ./...
      - go tool cover -func coverage.out

  coverage_html:
    cmds:
      - go tool cover -html coverage.out -o cover.html
